Django-Scraper/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Scrapy.urls")),
]

Scrapy/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.welcome, name="welcome"),
    path('scrapy', views.Scrapy, name="scrapy"),
    path('dataScraping', views.dataScraping, name="dataScraping"),
]

Scrapy/models.py
from django.db import models

# Create your models here.


class data(models.Model):
    x = models.CharField(max_length=200)

Scrapy/forms.py
from django import forms


class ScrapForm(forms.Form):
    UrlsName = forms.CharField(label="Enter urls",max_length=500)

Django-Scraper/views.py
from django.shortcuts import render

# Create your views here.

def welcome(request):
    return ({'bands': "ok"})

Scrapy/views.py
'''Date - July 2020 '''
'''Author - Sudhir kumar'''


from django.shortcuts import render, redirect, HttpResponse
from .forms import ScrapForm
import time, os, json, re
from django.views.decorators.csrf import csrf_exempt

print(os.listdir(os.getcwd()))

def findUrls(strings):
    try:
        res =  "".join(strings.split())
        res =  res.replace(",", "")
        res = strings.replace("http", ",http")
        res = res.split(",")
        res = " ".join(res).split()
        return  res
    except:
        res = "".join(strings.split())
        res = strings.replace("http", ",http")
        res = res.split(",")
        res = " ".join(res).split()
        return res


def welcome(request):
    return HttpResponse("welcome to scrapy application | for scrapy goto /scrapy")

def Scrapy(request):
    student = ScrapForm()
    return render(request, "form.html",{'form':student})

items = []
def collect_items(item, response, spider):
    items.append(item)

@csrf_exempt
def dataScraping(request):
    eachUrls = []
    if request.method == 'POST':
        form = ScrapForm(request.POST)
        urls = form.data['UrlsName']
        eachUrls = findUrls(urls)
        for x in eachUrls:
            link = x
            path = os.getcwd()
            os.chdir(path + "/UrlScraper")
            cmd = 'scrapy crawl scraperBot -a start_url="{}" -t json -o outputfile.json'.format(link)
            r = os.system(cmd)
            os.chdir("../")

        try:
            path = os.getcwd()
            print("pth==", path)
            os.chdir(path + "/UrlScraper")
            print("-=0ok", os.getcwd())
            newpth = path+"/UrlScraper"
            x = open(newpth + "/outputfile.json", "r")
            x = x.read()
            if len(x) > 5:
                x = x.replace('][', ',')
                f = open(newpth + "/FinalOp.json", "w")
                f.write(x)
                f.close()
                with open(newpth + '/FinalOp.json') as f:
                    data = json.load(f)
                os.remove(newpth + "/outputfile.json")
                os.remove(newpth + "/FinalOp.json")
                os.chdir("../")
                print(os.listdir(os.getcwd()))

                return HttpResponse(json.dumps(data))
            else:
                return HttpResponse(json.dumps({"Status":"UrlErr"}))
        except:
            return ({"Status": "UrlErr"})
    else:
        return HttpResponse({"Status": "RequestErr"})

templates/Scraper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    #formsection{
        margin-left: auto;
        margin-right: auto;
        width: auto;
        height: auto;
        border: 1px red solid;
        padding: 12px;
    }
    #txtfield, #submit{
        width: 50%;
        padding: 8px;
        border-radius: 5px;

    }
</style>
<body>

<section id="formsection">
    <form action="/dataScraping" method="post">
        <input type="text" id="txtfield"><br><br>
        <input type="submit" id="submit">
    </form>
</section>


</body>
</html>

templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <style>
        #form-box {
            width:300px;
            padding:30px 5%;
            margin:30px auto;
            border-radius:5px;
         border: 1px solid #ddd;
        box-shadow: 2px 0 7px #eee;
        text-align: center;
        background: #f5f5f5;
        }
        #form-box label {
            text-align:left;
                font-family: monospace;
    font-size: 20px;
        }
        #form-box input {
            padding:3px 10px;
            width:280px;
        }
        #form-box button {
            background:#007ae2;
            color:#fff;
            padding:5px 10px;
            width:100%;
            text-align:center;
            font-family: monospace;
            font-size: 20px;
            outline:none;
            border:0;
        }
        #myProgress {
            display:none;
            width: 80%;
            position:relative;
            margin:0 auto 20px;
            background-color: #ddd;
}
#dataList {
    word-break: break-all;
    width:80%;
    padding:0 15px 10px;
    font-family: tahoma;
    margin:auto;
    font-size:15px;
    border: 1px solid #ddd;
}
#error-box {
    padding: 30px;
    text-align: center;
    width: 60%;
    margin: auto;
    font-size: 26px;
    border: 1px solid #ddd;
    background: #f5f5f5;
    border-radius: 5px;
    font-family: tahoma;
    color: #b70000;
}
#myBar {
  width: 1%;
  height: 30px;
  background-color: #4CAF50;
}
        #perc { position:absolute;left:0;right:0;margin:auto;z-index:1;top:3px;text-align:center;color:#333;}
    </style>
</head>
<body>

<div id="form-box">
<form method="POST" class="post-form"  id="txt">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="button" class="save btn btn-default" id="btn" >Sumbit</button>
</form>
</div>
<div id="myProgress">
  <div id="myBar"></div>
    <span id="perc"></span>
</div>
<div id="dataList">
</div>
<input type="hidden" value="" />
<br><br><br>

<script>
        var x;
        var j = 0;
        var k = 0;

        $(document).ready(function () {
            $("#btn").click(function () {
                document.getElementById('dataList').innerHTML = '';
                stop();
              start();
                var inVal = $('#id_UrlsName').val();
                $.ajax({
                    type: 'post',
                    url: '/dataScraping',
                    data: {UrlsName: inVal},
                    success: function (data) {
                          clearInterval(timer);
                        document.getElementById('perc').innerHTML = "100%";
                        document.getElementById("myBar").style.width = "100%";
                        var Jdata = JSON.parse(data);
                        if(Jdata.Status == "UrlErr"){
                            $('body').html("<div id='error-box'>Sorry ! You have entered wrong Url</div>");
                        }
                        if(Jdata.Status == "RequestErr"){
                             $('body').html("<div id='error-box'>Sorry ! Only Post Request Accepted</div>")
                        }

                        Jdata.map(obj => {
                            console.log(obj);
                            var key = Object.keys(obj)[0];
                            {#console.log(Object.keys(obj)[0]);#}
                            var inneritem = obj[key];
                            {#console.log(x[1]);#}
                            var y = inneritem.length;
                            $("#dataList").append("<h3>" + Object.keys(obj) + "</h3>");
                            {#document.getElementById('dataList').innerHTML = Object.keys(obj) + "<br />";#}
                            k++;
                            for (var i = 0; i < y; i++) {
                                j++;
                                if (j > 100) {
                                    break;
                                }
                                else {
                                    $("#dataList").append(j + ". " + inneritem[i] + "<br>");
                                }
                            }
                            j = 0;
                        })
                    }
                })

            });

        });

var timer = null,
  interval = 200,
  value = 0;
function start(){
    $("#myProgress").show();
  value = 0;
  $("#myBar").css('width',"0%");
  $("#perc").html("");
  if (timer !== null) return;
  timer = setInterval(function () {
      value = value+1;
      $("#myBar").css('width',value + "%");
      $("#perc").html(value + "%");
      if(value >= 100){
        clearInterval(timer);
      }
  }, interval);

}
function stop(){
  clearInterval(timer);
  timer = null
}

</script>
<p> {{ Status }}</p>
</body>
</html>

templates/output.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<script>

        let x = {{data|safe}};
        var j = 0;var k =0;
        x.map(obj=>{
            console.log(obj);
            var key = Object.keys(obj)[0];
            {#console.log(Object.keys(obj)[0]);#}
            var inneritem = obj[key];
            {#console.log(x[1]);#}
            var y = inneritem.length;
            document.write(Object.keys(obj) + "<br>");

            k++;
            for (var i=0; i<y;i++){
                j++;
                if(j > 100)
                {
                    break;
                }
                else {
                    document.write(j + ". " + inneritem[i] + "<br>")
                }
            }
            j=0;
             document.write("------------------------------------------------------------------------<br>")
        })
</script>
<pre id="json"></pre>

</body>
</html>